//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Microsoft.MixedReality.Toolkit.Experimental.InteractiveElement.FocusInteractionEvent))]
	public class PropertyProvider_Microsoft_MixedReality_Toolkit_Experimental_InteractiveElement_FocusInteractionEvent : Unity.VisualScripting.SerializedPropertyProvider<Microsoft.MixedReality.Toolkit.Experimental.InteractiveElement.FocusInteractionEvent>
	{
	}
}
